"use client";

import { useMemo, useState } from "react";
import { fallbackDecisions } from "@/lib/data";
import type { Decision, DecisionStatus } from "@/lib/types";
import DecisionCard from "./DecisionCard";

export default function DecisionBoard() {
  const [decisions, setDecisions] = useState<Decision[]>(fallbackDecisions);
  const [loading, setLoading] = useState(false);
  const [source, setSource] = useState<"fallback" | "ai" | null>(null);

  function updateStatus(id: string, status: DecisionStatus) {
    setDecisions((prev) =>
      prev.map((d) => (d.id === id ? { ...d, status } : d))
    );
  }

  function askAbout(decision: Decision) {
    const el = document.getElementById("ask");
    el?.scrollIntoView({ behavior: "smooth" });
  }

  async function generate() {
    setLoading(true);
    try {
      const res = await fetch("/api/analyze-finances", { method: "POST" });
      const data = await res.json();
      if (Array.isArray(data.decisions) && data.decisions.length) {
        setDecisions(data.decisions);
        setSource(data.source ?? "ai");
      }
    } catch {
      setDecisions(fallbackDecisions);
      setSource("fallback");
    } finally {
      setLoading(false);
    }
  }

  const approved = useMemo(
    () => decisions.filter((d) => d.status === "Approved"),
    [decisions]
  );
  const reviewLater = useMemo(
    () => decisions.filter((d) => d.status === "Review Later"),
    [decisions]
  );

  return (
    <section id="decisions" className="bg-slate-50">
      <div className="mx-auto max-w-6xl px-6 py-16">
        <div className="flex flex-wrap items-end justify-between gap-4">
          <div>
            <h2 className="text-2xl font-bold text-navy">AI Decision Board</h2>
            <p className="mt-1 text-slate-500">
              A clear approval list of money decisions. You have the final say.
            </p>
          </div>
          <div className="flex items-center gap-3">
            {source ? (
              <span className="text-xs text-slate-400">
                {source === "ai"
                  ? "Generated by AgentCFO AI"
                  : "Showing built-in recommendations"}
              </span>
            ) : null}
            <button
              type="button"
              onClick={generate}
              disabled={loading}
              className="rounded-xl bg-brand px-5 py-2.5 text-sm font-semibold text-white transition hover:bg-brand-dark disabled:opacity-50"
            >
              {loading ? "Analyzing…" : "Generate AI CFO Recommendations"}
            </button>
          </div>
        </div>

        <div className="mt-8 grid grid-cols-1 gap-6 lg:grid-cols-2">
          {decisions.map((d) => (
            <DecisionCard
              key={d.id}
              decision={d}
              onUpdate={updateStatus}
              onAsk={askAbout}
            />
          ))}
        </div>

        <div className="mt-12 grid grid-cols-1 gap-6 md:grid-cols-2">
          <TrackingList
            title="Owner-Approved Actions"
            empty="No actions approved yet."
            items={approved}
            accent="text-green-600"
          />
          <TrackingList
            title="Review Later"
            empty="Nothing set aside to review."
            items={reviewLater}
            accent="text-amber-600"
          />
        </div>
      </div>
    </section>
  );
}

function TrackingList({
  title,
  empty,
  items,
  accent,
}: {
  title: string;
  empty: string;
  items: Decision[];
  accent: string;
}) {
  return (
    <div className="rounded-2xl border border-slate-100 bg-white p-6 shadow-card">
      <h3 className={`text-lg font-semibold ${accent}`}>{title}</h3>
      {items.length === 0 ? (
        <p className="mt-3 text-sm text-slate-400">{empty}</p>
      ) : (
        <ul className="mt-4 space-y-3">
          {items.map((d) => (
            <li
              key={d.id}
              className="flex items-center justify-between gap-3 rounded-xl bg-slate-50 px-4 py-3"
            >
              <span className="text-sm font-medium text-navy">{d.title}</span>
              <span className="text-sm text-slate-500">{d.amount}</span>
            </li>
          ))}
        </ul>
      )}
    </div>
  );
}
